#!/usr/bin/env python3
"""Turns tools/dex_popularity/pokemon-survey-results.csv into src/data/dex_popularity.h.

The CSV has one row per Pokémon (Rank, Dex #, Base Species, Votes). Some forms have
their own rows (e.g. Charizard X/Y); their votes are added to the base species.
Dex numbers are matched to the NATIONAL_DEX_* constants, so names in the CSV don't matter.

Run from the repo root: python3 tools/dex_popularity/make_dex_popularity.py
"""
import csv
import re
import sys

CSV_PATH = "tools/dex_popularity/pokemon-survey-results.csv"
DEX_ENUM_PATH = "include/constants/pokedex.h"
OUTPUT_PATH = "src/data/dex_popularity.h"
SOURCE_URL = "https://docs.google.com/spreadsheets/d/1bGJqCYBdT8LEaKARb0fCfrVePl90yN77CtJMvIVd0IE"


def read_dex_constants():
    names = []
    with open(DEX_ENUM_PATH, encoding="utf-8") as f:
        for line in f:
            match = re.match(r"\s*(NATIONAL_DEX_\w+)\s*,", line)
            if match and match.group(1) != "NATIONAL_DEX_NONE":
                names.append(match.group(1))
            if match and match.group(1) == "NATIONAL_DEX_PECHARUNT":
                break
    return names


def main():
    dex_names = read_dex_constants()
    votes = {}
    with open(CSV_PATH, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            dex = int(row["Dex #"])
            if not 1 <= dex <= len(dex_names):
                sys.exit(f"Dex # {dex} ({row['Base Species']}) is outside the National Dex")
            votes[dex] = votes.get(dex, 0) + int(row["Votes"])

    missing = [dex_names[i - 1] for i in range(1, len(dex_names) + 1) if i not in votes]
    if missing:
        print(f"Warning: no votes for {len(missing)} species: {', '.join(missing)}", file=sys.stderr)

    width = max(len(name) for name in dex_names)
    lines = [
        "// Generated by tools/dex_popularity/make_dex_popularity.py from tools/dex_popularity/pokemon-survey-results.csv. Don't edit by hand.",
        f"// Popularity survey votes per National Dex species ({SOURCE_URL}).",
        "// Votes for alternate forms are added to their base species.",
        "",
        "static const u16 sDexSurveyVotes[NATIONAL_DEX_PECHARUNT + 1] =",
        "{",
    ]
    for dex in sorted(votes):
        name = dex_names[dex - 1]
        lines.append(f"    [{name}]{' ' * (width - len(name))} = {votes[dex]},")
    lines.append("};")

    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {len(votes)} species to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
