#ifndef GUARD_GENERATED_ANIM_CODE_GeneralPorytiles_H
#define GUARD_GENERATED_ANIM_CODE_GeneralPorytiles_H

// Ensure INCBIN_U16 is available
#ifndef INCBIN_U16
#include "gba/defines.h"
#endif

/*
 * This file is auto-generated by Porytiles.
 * DO NOT EDIT THIS FILE MANUALLY (unless you know what you are doing).
 */

// ============================================
// Frame Data (INCBIN statements)
// ============================================

const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame0[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_a/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame1[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_a/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame2[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_a/2.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame3[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_a/3.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame4[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_a/4.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame5[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_a/5.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame6[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_a/6.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame7[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_a/7.4bpp");

const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame0[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_b/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame1[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_b/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame2[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_b/2.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame3[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_b/3.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame4[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_b/4.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame5[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_b/5.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame6[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_b/6.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame7[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/calm_water_b/7.4bpp");

const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_Flower_Frame0[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/flower/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_Flower_Frame1[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/flower/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_Flower_Frame2[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/flower/2.4bpp");

const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_FlowerWhite_Frame0[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/flower_white/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_FlowerWhite_Frame1[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/flower_white/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_FlowerWhite_Frame2[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/flower_white/2.4bpp");

const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame0[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame1[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame2[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge/2.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame3[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge/3.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame4[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge/4.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame5[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge/5.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame6[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge/6.4bpp");

const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame0[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge_b/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame1[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge_b/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame2[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge_b/2.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame3[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge_b/3.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame4[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge_b/4.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame5[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge_b/5.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame6[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/sand_water_edge_b/6.4bpp");

const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame0[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/shallow_water/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame1[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/shallow_water/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame2[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/shallow_water/2.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame3[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/shallow_water/3.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame4[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/shallow_water/4.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame5[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/shallow_water/5.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame6[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/shallow_water/6.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame7[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/shallow_water/7.4bpp");

const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame0[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_edge/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame1[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_edge/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame2[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_edge/2.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame3[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_edge/3.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame4[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_edge/4.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame5[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_edge/5.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame6[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_edge/6.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame7[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_edge/7.4bpp");

const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_Waterfall_Frame0[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/waterfall/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_Waterfall_Frame1[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/waterfall/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_Waterfall_Frame2[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/waterfall/2.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_Waterfall_Frame3[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/waterfall/3.4bpp");

const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame0[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_rock/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame1[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_rock/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame2[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_rock/2.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame3[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_rock/3.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame4[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_rock/4.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame5[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_rock/5.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame6[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_rock/6.4bpp");
const u16 gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame7[] = INCBIN_U16("data/tilesets/primary/general_porytiles/porytiles_bin/anim/water_rock/7.4bpp");

// ============================================
// Frame Pointer Arrays
// ============================================

const u16 *const gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA[] = {
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame0,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame1,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame2,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame3,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame4,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame5,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame6,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA_Frame7
};

const u16 *const gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB[] = {
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame0,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame1,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame2,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame3,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame4,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame5,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame6,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB_Frame7
};

const u16 *const gTilesetAnims_PorytilesManaged_GeneralPorytiles_Flower[] = {
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_Flower_Frame0,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_Flower_Frame1,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_Flower_Frame0,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_Flower_Frame2
};

const u16 *const gTilesetAnims_PorytilesManaged_GeneralPorytiles_FlowerWhite[] = {
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_FlowerWhite_Frame0,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_FlowerWhite_Frame1,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_FlowerWhite_Frame0,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_FlowerWhite_Frame2
};

const u16 *const gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge[] = {
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame0,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame1,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame2,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame3,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame4,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame5,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame6,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge_Frame0
};

const u16 *const gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB[] = {
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame0,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame1,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame2,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame3,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame4,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame5,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame6,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB_Frame0
};

const u16 *const gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater[] = {
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame0,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame1,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame2,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame3,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame4,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame5,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame6,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater_Frame7
};

const u16 *const gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge[] = {
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame0,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame1,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame2,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame3,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame4,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame5,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame6,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge_Frame7
};

const u16 *const gTilesetAnims_PorytilesManaged_GeneralPorytiles_Waterfall[] = {
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_Waterfall_Frame0,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_Waterfall_Frame1,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_Waterfall_Frame2,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_Waterfall_Frame3
};

const u16 *const gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock[] = {
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame0,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame1,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame2,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame3,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame4,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame5,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame6,
    gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock_Frame7
};

// ============================================
// Queue Functions
// ============================================

static void QueueAnimTiles_PorytilesManaged_GeneralPorytiles_CalmWaterA(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterA[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(1)), 1 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_PorytilesManaged_GeneralPorytiles_CalmWaterB(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_GeneralPorytiles_CalmWaterB[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(2)), 1 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_PorytilesManaged_GeneralPorytiles_Flower(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_GeneralPorytiles_Flower);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_GeneralPorytiles_Flower[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(3)), 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_PorytilesManaged_GeneralPorytiles_FlowerWhite(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_GeneralPorytiles_FlowerWhite);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_GeneralPorytiles_FlowerWhite[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(7)), 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_PorytilesManaged_GeneralPorytiles_SandWaterEdge(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdge[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(11)), 6 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(17)), 2 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_PorytilesManaged_GeneralPorytiles_ShallowWater(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_GeneralPorytiles_ShallowWater[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(19)), 2 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_PorytilesManaged_GeneralPorytiles_WaterEdge(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterEdge[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(21)), 4 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_PorytilesManaged_GeneralPorytiles_Waterfall(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_GeneralPorytiles_Waterfall);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_GeneralPorytiles_Waterfall[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(41)), 6 * TILE_SIZE_4BPP);
}

static void QueueAnimTiles_PorytilesManaged_GeneralPorytiles_WaterRock(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_GeneralPorytiles_WaterRock[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(25)), 16 * TILE_SIZE_4BPP);
}

// ============================================
// Driver Function
// ============================================

static void TilesetAnim_PorytilesManaged_GeneralPorytiles(u16 timer)
{
    if (timer % 16 == 0)
    {
        QueueAnimTiles_PorytilesManaged_GeneralPorytiles_Flower(timer / 16);
        QueueAnimTiles_PorytilesManaged_GeneralPorytiles_FlowerWhite(timer / 16);
    }
    if (timer % 16 == 1)
    {
        QueueAnimTiles_PorytilesManaged_GeneralPorytiles_CalmWaterA(timer / 16);
        QueueAnimTiles_PorytilesManaged_GeneralPorytiles_CalmWaterB(timer / 16);
        QueueAnimTiles_PorytilesManaged_GeneralPorytiles_ShallowWater(timer / 16);
        QueueAnimTiles_PorytilesManaged_GeneralPorytiles_WaterEdge(timer / 16);
        QueueAnimTiles_PorytilesManaged_GeneralPorytiles_WaterRock(timer / 16);
    }
    if (timer % 16 == 2)
    {
        QueueAnimTiles_PorytilesManaged_GeneralPorytiles_SandWaterEdge(timer / 16);
        QueueAnimTiles_PorytilesManaged_GeneralPorytiles_SandWaterEdgeB(timer / 16);
    }
    if (timer % 16 == 3)
    {
        QueueAnimTiles_PorytilesManaged_GeneralPorytiles_Waterfall(timer / 16);
    }
}

// ============================================
// Init Function
// ============================================

void InitTilesetAnim_PorytilesManaged_GeneralPorytiles(void)
{
    sPrimaryTilesetAnimCounter = 0;
    sPrimaryTilesetAnimCounterMax = 256;
    sPrimaryTilesetAnimCallback = TilesetAnim_PorytilesManaged_GeneralPorytiles;
}

#endif // GUARD_GENERATED_ANIM_CODE_GeneralPorytiles_H
